repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Utilisez la version la plus récente ou adaptée
    hooks:
      - id: trailing-whitespace
        exclude: ^doc/_build/
      - id: end-of-file-fixer
        exclude: ^doc/_build/
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=99]
