# Exemple de configuration dans Dockerfile.nginx
FROM nginx:1.21

# Copier le fichier de configuration nginx.conf dans le conteneur
COPY nginx.conf /etc/nginx/nginx.conf

# Copie du contenu du répertoire 'static' vers le répertoire racine de NGINX
COPY ./static /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

# CMD pour démarrer nginx (peut être automatiquement pris en charge par l'image nginx)
CMD ["nginx", "-g", "daemon off;"]

