# Generated by Django 5.0.6 on 2024-07-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_auto_20240628_1217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "addresses"},
        ),
    ]
