# Generated by Django 5.0.6 on 2024-06-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
